package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestRunVersionAndUnknown(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"version"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("mizan")) {
		t.Fatalf("unexpected version output: %s", stdout.String())
	}
	if err := Run(context.Background(), []string{"nope"}, &stdout, &stderr); err == nil {
		t.Fatal("expected unknown command error")
	}
}

func TestServeInvalidBindReturnsError(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), []string{"serve", "--home", t.TempDir(), "--bind", "bad address"}, &stdout, &stderr)
	if err == nil {
		t.Fatal("expected serve error for invalid bind")
	}
}

func TestProjectGenerateValidateAndSnapshotCommands(t *testing.T) {
	home := t.TempDir()
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"project", "new", "--home", home, "--name", "edge", "--engines", "haproxy,nginx"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	if created.Project.ID == "" {
		t.Fatal("missing project id")
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"project", "list", "--home", home}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("edge")) {
		t.Fatalf("project list missing edge: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"generate", "--home", home, "--project", created.Project.ID, "--target", "haproxy"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("Generated by Mizan")) {
		t.Fatalf("generate output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"validate", "--home", home, "--project", created.Project.ID, "--target", "haproxy"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte(`"target":"haproxy"`)) {
		t.Fatalf("validate output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "list", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var snapshots []string
	if err := json.Unmarshal(stdout.Bytes(), &snapshots); err != nil {
		t.Fatal(err)
	}
	if len(snapshots) == 0 {
		t.Fatal("expected snapshots")
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "tag", "--home", home, "--project", created.Project.ID, "--label", "release", snapshots[0]}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "get", "--home", home, "--project", created.Project.ID, "release"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "revert", "--home", home, "--project", created.Project.ID, "release"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "tags", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("release")) {
		t.Fatalf("tags output unexpected: %s", stdout.String())
	}
}

func TestProjectImportAndDelete(t *testing.T) {
	home := t.TempDir()
	cfgPath := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := os.WriteFile(cfgPath, []byte("frontend web\n  bind :80\n  default_backend be_app\nbackend be_app\n  server app 127.0.0.1:8080\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"project", "import", "--home", home, "--name", "imported", cfgPath}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	if err := Run(context.Background(), []string{"project", "delete", "--home", home, created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
}

func TestParseEngines(t *testing.T) {
	engines := parseEngines("haproxy,nginx,bad")
	if len(engines) != 2 {
		t.Fatalf("engines=%v", engines)
	}
}
